### PR TITLE
Proxy Credentials - use Default Cache

### PR DESCRIPTION
**Pull request by processedbeets**
Allow Proxy Credentials to be pulled from the Default Network
Credentials Cache. Allows posting to Slack whilst debugging in Visual
Studio on a private domain.

### CODE REVIEW

**Comment by cyrilgandon** [comment]
Looks good, thank you!

**Comment by processedbeets** [comment]
No problem. Can I trouble you to upload a new version to NuGet please? I'm happy to tweak the NuSpec file if you like?

**Comment by cyrilgandon** [comment]
@processedbeets it's done! I upgrade to v4.2 to reflect minor version dependency on NLog

**Comment by processedbeets** [comment]
Brilliant, good man. Thanks for that. I opted for your version of the
library as you'd dropped the required .net version to 4 which meant we
could install on windows 2003 servers. Good job! :)

**Comment by cyrilgandon** [comment]
Good to see we are not the only team to have windows server 2003!! :)

**Pull request merged**
